### ISSUE TITLE
Total number of pages

### ISSUE THREAD

**Issue by AlagaiKa** [OptimiliaStudios/AquileReader#67] opened 2021-12-01 15:47 UTC
Is it possible to show the ***total number of pages*** in the book? I can only see the _chapter pages_, but I don't really need that feature.
Thank you!

**Comment by OptimiliaStudios** [comment] 2021-12-18 13:52
Duplicate of #47

**Comment by OptimiliaStudios** [comment] 2021-12-18 13:54
Posting the original response

> Right now I render only one chapter at a time, and the page count changes based on the size of the app window. To know the total page count of the book means either I'll have to load all the chapters **(which will make the book load slow)** or I'll have to come up with some guess estimate page count which might change when the chapter actually loads, and I don't think it will be a good experience seeing total page count change.
> Let me know what you think.
> 
> I'll see if there is some other way to do it which is more deterministic, but cannot commit on this feature.

**Closed** 2021-12-18 13:55 UTC
Labels: duplicate, enhancement, backlog
