### ISSUE TITLE
Blank page when opening: "Designing Data-Intensive Applications"

### ISSUE THREAD

**Issue by rubin55** [OptimiliaStudios/AquileReader#35] opened 2021-05-08 12:48 UTC
When attempting to open "Designing Data-Intensive Applications", Aquile shows a blank page. The table of contents does show, but selecting any entry does not return a page. It does change the percentage completed.

I've sent you the file via [WeTransfer](https://wetransfer.com/) on your email address: optimilia.studios@gmail.com. Note that the transfer is only valid for 7 days.

**Comment by OptimiliaStudios** [comment] 2021-05-10 15:38
Duplicate of #31

**Closed by OptimiliaStudios** 2021-05-10 15:38 UTC
