### ISSUE TITLE
How to disable the tooltip that appears when I hover the mouse over the book lines

### ISSUE THREAD

**Issue by nurlanmikayilov** [OptimiliaStudios/AquileReader#76] opened 2022-02-04 06:39 UTC
Hi, I want to disable the tooltip that appears when I hover the mouse over the book lines. This really distracts me.

**Comment by OptimiliaStudios** [comment] 2022-02-04 17:06
Can you plz share screenshot of what exactly you are referring to?

**Comment by nurlanmikayilov** [comment] 2022-02-05 07:35
![WhatsApp Image 2022-02-05 at 11 33 10 AM](https://user-images.githubusercontent.com/33370655/152633143-6d2a764e-24c5-4fd8-8a90-55837d1e2a21.jpeg)

**Comment by ac-lap** [comment] 2022-02-05 08:46
I am not able to reproduce the issue. Does it happen with all books or just this book? It's possible that book has this tooltip.

**Comment by OptimiliaStudios** [comment] 2022-02-05 08:47
I am not able to reproduce the issue. Does it happen with all books or just this book? 
Will it be possible to share the epub file of the book on which you are facing this issue? It's possible that book has this tooltip.

optimilia.studios@gmail.com

**Comment by nurlanmikayilov** [comment] 2022-02-05 12:10
I tried a few other books and Identified that this occurs in some of them.

**Comment by OptimiliaStudios** [comment] 2022-04-15 04:22
Closing the issue as the tooltip issue is specific to books and not the app.

**Closed by OptimiliaStudios** 2022-04-15 04:22 UTC
